# Generated by Django 4.1.3 on 2022-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('running_workers', models.IntegerField(default=0)),
            ],
        ),
    ]
