# Generated by Django 4.1.3 on 2022-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1000)),
                ('demand_price', models.IntegerField(max_length=50)),
            ],
        ),
    ]
