# Generated by Django 4.1.3 on 2022-12-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_worker_data_demand_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_data',
            name='client_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
